version: '3.8'
services:
  backend:
    build: .
    ports:
      - "9001:9001"
    working_dir: /app
  frontend:
    build: ./trading-frontend
    ports:
      - "3000:3000"
    working_dir: /app
    depends_on:
      - backend